---
layout: post
title: "JavaScript 异步编程 -- Promise"
date: 2017-06-03
description: "Promise 的使用及简单实现"
tag: JavaScript
---

### 为什么需要 Promise

一直以来，JavaScript 处理异步都是以 callback 的方式，但是存在多层依赖的话，我们的代码会变得难以管理，也就是所谓的回调地狱。

比如我们想获取一个用户的朋友的个人信息，但是后台没有提供这个接口，我们只能通过：

-    获取用户的朋友列表，从朋友列表中取出相应朋友的用户 id 
-    然后通过这个 id 去查询该朋友的个人信息
-    最后展示该信息

以 callback 的方式我们可能这样写: 

```JavaScript
getUserFriends(id, index, (friends) => {
    getFriendInfoById(friends[index].id, () => {
        showFriendInfo();
    });
});
```

ES6 标准已经引入了 Promise 。如果我们用 Promise 来写，看起来和管理起来都会方便许多,而且我们可以很方便在最后统一做错误处理:

```JavaScript
getUserFriends(id, index)
    .then(getFriendInfoById)
    .then(showFriendInfo)
    .catch((error) => {
        console.log(error);
    });
```

### Promise 规范

-    一个 Promise 可能有三种状态：等待( pending )、已完成( fulfilled )、已拒绝( rejected )
-    一个 Promise 的状态只可能从“等待”转到“完成”态或者“拒绝”态，不能逆向转换，同时“完成”态和“拒绝”态不能相互转换
-    Promise 必须实现 then 方法(可以说，then 就是 Promise 的核心)，而且 then 必须返回一个 Promise ，同一个 Promise 的 then 可以调用多次，并且回调的执行顺序跟它们被定义时的顺序一致
-    then 方法接受两个参数，第一个参数是成功时的回调，在 Promise 由“等待”态转换到“完成”态时调用，另一个是失败时的回调，在 Promise 由“等待”态转换到“拒绝”态时调用。同时，then 可以接受另一个 Promise 传入，也接受一个“类 then ”的对象或方法，即 thenable 对象

### 使用 Promise

#### Promise 的立即执行性

```JavaScript
let promise = new Promise((resolve, reject) => {
    console.log("promise");
    resolve("then");
});

console.log("global");

promise.then((res) => {
    console.log(res);
});
```

控制台打印结果:

```JavaScript
"promise"
"global"
"then"
```

我们在创建 promise 实例对象时，向构造函数 Promise 传入的函数是**立即执行**的，只是其中的代码可以是异步代码。

#### Promise 三种状态

```JavaScript
let promise0 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve("0");
    }, 500);
});

let promise1 = new Promise((resolve, reject) => {
    resolve("1");
});

let promise2 = new Promise((resolve, reject) => {
    reject("2");
});

console.log(promise0);
console.log(promise1);
console.log(promise2);

setTimeout(() => {
    console.log(promise0);
}, 1000);

promise0.then((res) => {
    console.log(res);
});
promise1.then((res) => {
    console.log(res);
});
promise2.catch((res) => {
    console.log(res);
});
```

控制台打印结果:

```JavaScript
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: "1"}
Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: "2"}
1
2
// 延迟 500ms 后触发 promise0 then 里面的函数
0
// 延迟 1000ms 后打印 promise0 ，此时 promise0 状态已经变化
Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: "0"}
```

由此可见，Promise 内部实现是一个状态机。

**Promise 有三种状态: pending , resolved , rejected**。

当 Promise 刚创建完成时，处于 pending 状态；当 Promise 中的 resolve 方法执行后，状态由 pending 变成 resolved ；如果执行的不是 resolve 方法，而是 reject 方法，状态由 pending 变成 rejected 。

#### Promise 状态的不可逆性

```JavaScript
let promise0 = new Promise((resolve, reject) => {
    resolve("promise0");
    resolve("promise0 resolved");
});

let promise1 = new Promise((resolve, reject) => {
    reject("promise1 rejected");
    resolve("promise1");
});

console.log(promise0);
console.log(promise1);

promise0.then((res) => {
    console.log(res);
});

promise1
    .then((res) => {
        console.log(res);
    })
    .catch((error) => {
        console.log(error);
    })
```

控制台打印结果:

```JavaScript
Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: "promise0"}
Promise {[[PromiseStatus]]: "rejected", [[PromiseValue]]: "promise1 rejected"}
"promise0"
"promise1 rejected"
```

我们可以发现，Promise 对象只对第一次 resolve 方法或者 reject 方法做出了反应。因为 Promise 状态一旦变成 resolved 或者 reject 后，Promise 状态和值就固定下来了，不论后续再怎么调用 resolve 方法或者 reject 方法，都不能改变它的状态和值。

#### 链式调用

```JavaScript
let promise = new Promise((resolve, reject) => {
    resolve("promise");
});

promise
    .then((res) => {
        console.log(res);
        return res + "Resolved";
    })
    .then((res) => {
        console.log(res);
    })
    .then((res) => {
        console.log(res);
        return Promise.resolve("resolve");
    })
    .then((res) => {
        console.log(res);
        return Promise.reject("reject");
    })
    .then(() => {
        console.log("这里并不会执行");
    })
    .then(() => {
        console.log("这里还是不会执行");
    })
    .then((res) => {
        console.log(res);
    }, (error) => {
        console.log(error);
    });
    //
    // .catch 与 .then 中第二个参数相同
    // .catch((error) => {
    //     console.log(error);
    // });
    // 
    // .then(null ,function(){}) 也等同
    // .then(null, (error) => {
    //     console.log(error);
    // });
```

控制台打印结果:

```JavaScript
"promise"
"promiseResolved"
undefined
"resolve"
"reject"
```

Promise 对象的 then 方法返回一个新的 Promise 对象，因此可以通过链式调用 then 方法。then 方法接收两个函数作为参数，第一个参数是 Promise 执行成功时的回调，第二个参数是 Promise 执行失败时的回调。两个函数只会有一个被调用，函数的返回值将被用作创建 then 返回的 Promise 对象。这两个参数的返回值可以是以下三种情况中的一种：

-    return 一个同步的值 ，或者 undefined (当没有返回一个有效值时，默认返回 undefined )，then 方法将返回一个 resolved 状态的 Promise 对象，Promise 对象的值就是这个返回值
-    return 另一个 Promise ，then 方法将根据这个 Promise 的状态和值创建一个新的 Promise 对象返回
-    throw 一个同步异常，then 方法将返回一个 rejected 状态的 Promise , 值是该异常

在代码中有两处代码为执行，因为在它们之前调用了 reject 方法，调用 reject 方法后代码会直接跳到最后的错误处理，所以中间的代码被略过了。

#### Promise then() 回调异步性

```JavaScript
let promise = new Promise((resolve, reject) => {
    resolve("promise");
});

promise.then((res) => {
    console.log(res);
});

console.log("global");
```

控制台打印结果:

```JavaScript
"global"
"promise"
```

构造函数 Promise 接受的函数参数是同步执行的，但是 then 方法中的回调函数则是异步执行的，因此，" promise "会在" global "之后输出。这个涉及了事件循环的知识，我在[另一篇博文]()中对事件循环的知识点做了一点总结。

#### Promise 中的异常处理

```JavaScript
let promise0 = new Promise((resolve, reject) => {
    foo.bar();
    resolve("promise0");
});

let promise1 = new Promise((resolve, reject) => {
    resolve("promise1");
});

promise0
    .then((res) => {
        console.log(`p0 then value: ${res}`);
    }, (error) => {
        console.log(`p0 then error: ${error}`);
    })
    .then((res) => {
        console.log(`p0 then then value: ${res}`);
    }, (error) => {
        console.log(`p0 then then error: ${error}`);
    });

promise1
    .then((res) => {
        console.log(`p1 then value: ${res}`);
        foo.bar();
    }, (error) => {
        console.log(`p1 then error: ${error}`);
    })
    .then((res) => {
        console.log(`p1 then then value: ${res}`);
    }, (error) => {
        console.log(`p1 then then error: ${error}`);
        return 1;
    })
    .then((res) => {
        console.log(`p1 then then then value: ${res}`);
    }, (error) => {
        console.log(`p1 then then then error: ${error}`);
    });
```

控制台打印结果:

```JavaScript
p0 then error: ReferenceError: foo is not defined
p1 then value: promise1
p0 then then value: undefined
p1 then then error: ReferenceError: foo is not defined
p1 then then then value: 1
```

Promise 中的异常由 then 参数中的第二个回调函数处理，异常信息将作为 Promise 的值。异常一旦得到处理，异常处理后，then 返回的后续 Promise 对象将恢复正常，并会被 Promise 执行成功的回调函数。

#### Promise.resolve()

```JavaScript
let promise0 = Promise.resolve(0);
let promise1 = Promise.resolve(promise0);
let promise2 = new Promise((resolve, reject) => {
    resolve(0);
});
let promise3 = new Promise((resolve, reject) => {
    resolve(promise0);
});

console.log(promise0 === promise1);
console.log(promise0 === promise2);
console.log(promise0 === promise3);
console.log(promise2 === promise3);

promise3.then((res) => {
    console.log(`promise3 = ${res}`);
});
promise2.then((res) => {
    console.log(`promise2 = ${res}`);
});
promise1.then((res) => {
    console.log(`promise1 = ${res}`);
});
promise0.then((res) => {
    console.log(`promise0 = ${res}`);
});
```

控制台打印结果:

```JavaScript
true
false
false
false
promise2 = 0
promise1 = 0
promise0 = 0
promise3 = 0
```

Promise.resolve() 方法**可以接受一个值或者一个 Promise 对象作为参数**。

-    当参数是普通值时，返回一个 resolved 状态的 Promise 对象，对象的值就是这个参数
-    当参数是一个 Promise 对象时，**直接返回这个 Promise 对象**

通过 new 方式创建的 Promise 对象都是新的对象，因此后面的三个比较结果都是 false 。我们看到 promise3 的 then 最先调用，但却最后输出结果，这是因为 promise3 的 resolve 中接受的参数是一个 Promise 对象 promise0 ，resolve 方法会对 promise0 “拆箱”，得到 promise0 的状态和值，这个过程是异步的，所以最后输出。

#### resolve vs reject

```JavaScript
let promise0 = new Promise((resolve, reject) => {
    resolve(Promise.resolve("resolve"));
});

let promise1 = new Promise((resolve, reject) => {
    resolve(Promise.reject("reject"));
});

let promise2 = new Promise((resolve, reject) => {
    reject(Promise.resolve("resolve"));
});

promise0
    .then(fulfilled = (res) => {
        console.log(`promise0 fulfilled: ${res}`);
    }, rejected = (error) => {
        console.log(`promise0 rejected: ${error}`);
    });

promise1
    .then(fulfilled = (res) => {
        console.log(`promise1 fulfilled: ${res}`);
    }, rejected = (error) => {
        console.log(`promise1 rejected: ${error}`);
    });

promise2
    .then(fulfilled = (res) => {
        console.log(`promise2 fulfilled: ${res}`);
    }, rejected = (error) => {
        console.log(`promise2 rejected: ${error}`);
    });
```

控制台打印结果:

```JavaScript
promise2 rejected: [object Promise]
promise0 fulfilled: resolve
promise1 rejected: reject
```

**Promise 回调函数中的第一个参数 resolve ，会对 Promise 对象执行“拆箱”操作**。即当 resolve 的参数是一个 Promise 对象时，resolve 会“拆箱”获取这个 Promise 对象的状态和值，但这个过程是**异步的**。 promise0 “拆箱”后，得到的 Promise 对象的状态是 resolved ，因此 fulfilled 回调被执行，promise1 “拆箱”后得到 Promise 对象的状态是 rejected ，因此 rejected 回调被执行。**但 Promise 回调函数中第二个参数 reject 不具备“拆箱”能力**，reject 的参数会直接传递给 then 方法中的 rejected 回调，及时它接收的参数是一个状态为 resolved 的 Promise 对象。

#### Promise.all

```JavaScript
let promise0 = new Promise((resolve, reject) => {
    resolve("promise0");
});

let promise1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve("promise1");
    }, 1000);
});

promise0
    .then((res) => {
        console.log(new Date(), res);
    })
    .catch((error) => {
        console.log(new Date(), error);
    });

promise1
    .then((res) => {
        console.log(new Date(), res);
    })
    .catch((error) => {
        console.log(new Date(), error);
    });

Promise.all([promise0, promise1])
    .then((res) => {
        console.log(new Date(), res);
    });
```

控制台打印结果:

```JavaScript
Sun Jul 30 2017 21:25:29 GMT+0800 (中国标准时间) "promise0"
Sun Jul 30 2017 21:25:30 GMT+0800 (中国标准时间) "promise1"
Sun Jul 30 2017 21:25:30 GMT+0800 (中国标准时间) ["promise0", "promise1"]
```

Promise.all 接收一个 Promise 对象组成的数组作为参数，当这个数组所有的 Promise 对象状态都变成 resolved 或者 rejected 的时候，它才会调用 then 方法。

#### Promise.race

```JavaScript
let promise0 = new Promise((resolve, reject) => {
    resolve("promise0");
});

let promise1 = new Promise((resolve, reject) => {
    setTimeout(() => {
        resolve("promise1");
    }, 1000);
});

promise0
    .then((res) => {
        console.log(new Date(), res);
    })
    .catch((error) => {
        console.log(new Date(), error);
    });

promise1
    .then((res) => {
        console.log(new Date(), res);
    })
    .catch((error) => {
        console.log(new Date(), error);
    });

Promise.race([promise0, promise1])
    .then((res) => {
        console.log(new Date(), `race: ${res}`);
    });
```

控制台打印结果:

```JavaScript
Sun Jul 30 2017 21:34:21 GMT+0800 (中国标准时间) "promise0"
Sun Jul 30 2017 21:34:21 GMT+0800 (中国标准时间) "race: promise0"
Sun Jul 30 2017 21:34:22 GMT+0800 (中国标准时间) "promise1"
```

与 Promise.all 相似的是，Promise.race 都是以一个 Promise 对象组成的数组作为参数，不同的是，只要当数组中的其中一个 Promsie 状态变成 resolved 或者 rejected 时，就可以调用 .then 方法了。

> 参考文档
- [八段代码彻底掌握 Promise](https://juejin.im/post/597724c26fb9a06bb75260e8?utm_source=gold_browser_extension) 作者：xuchaobei
- [前端基础进阶（十三）：透彻掌握Promise的使用，读这篇就够了](http://www.jianshu.com/p/fe5f173276bd) 作者：波同学
- [JavaScript进阶之路——认识和使用Promise，重构你的Js代码](http://www.cnblogs.com/yunfeifei/p/4453690.html) 作者：雲霏霏